name: native_fire
description: "The Native Implementation of Fire packages for Windows"
homepage: https://github.com/RagehAz/native_fire.git
# ----------------------
publish_to: "none"
# --------------------------------------------------------------------------------
# BLDRS_APP_VERSION
version: 6.0.0
# ----------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  firebase_dart: 1.3.0
  firedart: 0.9.8
  # ------------------------------------
  basics:
    path: C:/dev/projects/bldrs_packs/basics
  #    git:
  #      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
dependency_overrides:
  intl: ^0.19.0
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
