name: native_fire
description: "The Native Implementation of Fire packages for Windows"
version: 4.2.0
publish_to: "none"
homepage: https://github.com/RagehAz/native_fire.git
# --------------------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  firebase_dart: ^1.1.4
  firedart: ^0.9.8
  http: ^1.1.0
  # ------------------------------------
  basics:
    path: D:/projects/bldrs_packs/basics
  #    git:
  #      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
dependency_overrides:
  intl: ^0.19.0
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
